lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
  
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
theme: leapday
description: Project page of Plug-and-Play Linearized ADMM
